name: Docker Build and Push

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            huntarr/huntarr
            ghcr.io/${{ github.repository_owner }}/huntarr
          tags: |
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=semver,pattern={{major}}
            type=schedule,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=dev,enable=${{ startsWith(github.ref, 'refs/heads/dev') }} 
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/build_cache:latest
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/build_cache:latest,mode=max
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.builder.outputs.OUTPUT_FILE }}
          path: ${{ steps.builder.outputs.OUTPUT_FILE }}
