name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: changelog-${{ github.run_number }}
          github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Parse tags
        id: parse_tags
        run: |
          git fetch -a
          echo "tag_count=$(git tag -l | wc -l)" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG
        continue-on-error: ${{ steps.parse_tags.outputs.tag_count == '1' }}
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
          artifacts: ${{ needs.build.outputs.OUTPUT_FILE }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md
